### ISSUE TITLE
Activation is an integer in QRNCell call

### ISSUE THREAD

**Issue by sachavakili** [yfletberliac/Mango#2]
See https://github.com/yfletberliac/Mango/blob/master/mango_squad.py#L222 :
`qrn = QRNCell(self.config.hidden_size_qrn, self.config.hidden_size_qrn)`

Triggers the following mistake:
```
    c = self._activation(linear(tf.concat(inputs, 1), self._num_units))

TypeError: 'int' object is not callable
```

Shouldn't you replace this line with :
`qrn = QRNCell(num_units=self.config.hidden_size_qrn)`
?

**Comment by yfletberliac** [comment]
Yes, thanks @sachavakili  :)
I fixed it some time ago but didn't get it to be committed - will do it right away.
